# !! File must end with empty line !!
dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
# Ephemeral MySQL database created in preview environment.
- name: mysql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~1.3.1
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: jx-test-jhipster
  repository: file://../jx-test-jhipster
